function run

%% Окно

fig = uifigure( ...
    'Name', 'Параметры расчёта', ...
    'Position', [400 100 600 650]);

uilabel(fig, ...
    'Position', [30 610 300 25], ...
    'Text', 'Параметры модели', ...
    'FontSize', 16, ...
    'FontWeight', 'bold');


%% ---------------- Параметры ----------------

% H.P0
uilabel(fig, ...
    'Position', [30 565 300 22], ...
    'Text', 'Давление на левой границе P0, Па');

H_P0 = uieditfield(fig, 'numeric', ...
    'Position', [380 565 150 22], ...
    'Value', 100);


% VerticalBC
uilabel(fig, ...
    'Position', [30 520 300 22], ...
    'Text', 'Верхняя/нижняя граница');

VerticalBC = uidropdown(fig, ...
    'Position', [380 520 150 22], ...
    'Items', {'Проницаемая', 'Непроницаемая'}, ...
    'Value', 'Непроницаемая', ...
    'ValueChangedFcn', @changeBoundary);


% V.P0
V_P0_label = uilabel(fig, ...
    'Position', [30 475 300 22], ...
    'Text', 'Давление V.P0, Па', ...
    'Visible', 'off');

V_P0 = uieditfield(fig, 'numeric', ...
    'Position', [380 475 150 22], ...
    'Value', 200, ...
    'Visible', 'off');


% mu1
uilabel(fig, ...
    'Position', [30 430 300 22], ...
    'Text', 'Вязкость воды μ1, Па·с');

mu1 = uieditfield(fig, 'numeric', ...
    'Position', [380 430 150 22], ...
    'Value', 1e-3);


% mu2/mu1
uilabel(fig, ...
    'Position', [30 385 300 40], ...
    'Text', {'Во сколько раз вязкость нефти', 'больше вязкости воды μ2 / μ1'});

muRatio = uieditfield(fig, 'numeric', ...
    'Position', [380 385 150 22], ...
    'Value', 4.3);


% L
uilabel(fig, ...
    'Position', [30 340 300 22], ...
    'Text', 'Длина капилляра L, м');

L = uieditfield(fig, 'numeric', ...
    'Position', [380 340 150 22], ...
    'Value', 9e-3);


% sigma
uilabel(fig, ...
    'Position', [30 295 300 22], ...
    'Text', 'Поверхностное натяжение σ, Н/м');

sigma = uieditfield(fig, 'numeric', ...
    'Position', [380 295 150 22], ...
    'Value', 7e-2);


% theta
uilabel(fig, ...
    'Position', [30 250 300 22], ...
    'Text', 'Угол смачивания θ, рад');

theta = uieditfield(fig, 'numeric', ...
    'Position', [380 250 150 22], ...
    'Value', pi/4);


%% ---------------- Площади ----------------

uilabel(fig, ...
    'Position', [30 205 250 40], ...
    'Text', {'Матрица площадей', 'горизонтальных капилляров A, м2'});

H_A = uitextarea(fig, ...
    'Position', [30 110 250 90], ...
    'Value', { ...
    '[1 1 1 1;', ...
    ' 1 2 1 1;', ...
    ' 1 1 1 1]'});


uilabel(fig, ...
    'Position', [320 205 250 40], ...
    'Text', {'Матрица площадей', 'вертикальных капилляров A, м2'});

V_A = uitextarea(fig, ...
    'Position', [320 110 250 90], ...
    'Value', { ...
    '[1 1 1;', ...
    ' 1 1 1;', ...
    ' 1 5 1;', ...
    ' 1 1 1]'});


%% ---------------- Кнопка ----------------

uibutton(fig, ...
    'Position', [190 35 220 45], ...
    'Text', 'Задать и запустить', ...
    'FontSize', 13, ...
    'ButtonPushedFcn', @startMain);


%% ============================================================
% Изменение типа границы
% ============================================================

    function changeBoundary(~, ~)

        isPermeable = strcmp( ...
            VerticalBC.Value, 'Проницаемая');

        V_P0.Visible = isPermeable;
        V_P0_label.Visible = isPermeable;

    end


%% ============================================================
% Создание Net и запуск main
% ============================================================

    function startMain(~, ~)

    %% Параметры

    Net.H.P0 = H_P0.Value;

    Net.VerticalBC = strcmp( ...
        VerticalBC.Value, 'Проницаемая');

    Net.V.P0 = V_P0.Value;

    Net.mu1 = mu1.Value;
    Net.mu2 = muRatio.Value * Net.mu1;

    Net.L = L.Value;

    Net.sigma = sigma.Value;
    Net.theta = theta.Value;


    %% Площади

    coef = pi*(100e-6)^2;

    Net.H.A = coef * str2num( ...
        strjoin(H_A.Value, ' '));

    Net.V.A = coef * str2num( ...
        strjoin(V_A.Value, ' '));


    %% Передаём Net в основной workspace
    
    assignin('base', 'Net', Net);
    
    %% Запускаем main в основном workspace
    
    evalin('base', 'main');
    
    %% Закрываем окно после запуска
    
    delete(fig);

end

end